pipeline:
  - name: zillot
    watchdog: 600
    git:
      url: https://github.com/mirmik/zillot
      name: zillot
    steps:
      - name: make
        run: ./make.py

      - name: test
        run: ./runtests

      - name: licant-libs
        run: licant-libs .

    success_info: "Pipeline: {{pipeline_name}}\nCommit: {{commit_hash}}\nMessage: {{commit_message}}\n"
