mkdir build-android
cd build-android
cmake .. -B . \
	-DCMAKE_CXX_COMPILER=${ACOMPILERS}/aarch64-linux-android29-clang++ \
	-DCMAKE_C_COMPILER=${ACOMPILERS}/aarch64-linux-android29-clang \
	-DWITHOUT_TESTS=1 \
	-DADDITIONAL_INCLUDES_IGRIS=${IGRIS_LIBRARY} \
	-DADDITIONAL_INCLUDES_NOS=${NOS_LIBRARY} \
	-DIGRIS_LIBRARY_PATH=${IGRIS_LIBRARY} \
	-DNOS_LIBRARY_PATH=${NOS_LIBRARY} \
	-DSTATIC_LIBS=1
make --debug