pipeline:
  - name: genos
    watchdog: 600
    git:
      url: https://github.com/mirmik/genos
      name: genos
      branch: master
    steps:
      - name: make
        run: ./make.py

    success_info: "Pipeline: zillot\nCommit: {{commit_hash}}\nMessage: {{commit_message}}\n"
