#ifndef NUCLEO_BOARDS
#define NUCLEO_BOARDS

#   define BOARD_HSE_FREQ 16000000
#	define SYSLED_GPIO GPIOA
#	define SYSLED_MASK (1<<5)
#	define SYSUART USART2
#	define SYSUART_IRQ USART2_IRQn
#	define SYSUART_RX_GPIO GPIOA
#	define SYSUART_TX_GPIO GPIOA
#	define SYSUART_RX_PIN 2
#	define SYSUART_TX_PIN 3
#	define SYSUART_TX_AF 7
#	define SYSUART_RX_AF 7

#endif