#ifndef RALGO_HEIMER_SIGNAL_TYPES_H
#define RALGO_HEIMER_SIGNAL_TYPES_H

#include <errno.h>

#define SIGNAL_TYPE_AXIS_STATE 1
#define SIGNAL_TYPE_SCALAR 2
#define SIGNAL_TYPE_DOF6 3

#define SIGNAL_TYPE_DATASIG_FLOAT 4
#define SIGNAL_TYPE_DATASIG_DOUBLE 5

#define SIGNAL_TYPE_PHASE_SIGNAL_BASE 6
#define SIGNAL_TYPE_PHASE1 6
#define SIGNAL_TYPE_PHASE2 7
#define SIGNAL_TYPE_PHASE3 8
#define SIGNAL_TYPE_PHASE4 9

#endif
