<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/posix/sys/time.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file<br>
&nbsp;*&nbsp;@brief<br>
&nbsp;*<br>
&nbsp;*&nbsp;@date&nbsp;12.09.11<br>
&nbsp;*&nbsp;@author&nbsp;Anton&nbsp;Bondarev<br>
&nbsp;*&nbsp;@author&nbsp;Ilia&nbsp;Vaprol<br>
&nbsp;*/<br>
<br>
#ifndef&nbsp;COMPAT_POSIX_SYS_TIME_H_<br>
#define&nbsp;COMPAT_POSIX_SYS_TIME_H_<br>
<br>
/*The&nbsp;time_t&nbsp;and&nbsp;suseconds_t&nbsp;types&nbsp;are&nbsp;defined&nbsp;as&nbsp;described&nbsp;in&nbsp;&lt;sys/types.h&gt;.*/<br>
#include&nbsp;&lt;igris/types-generic/suseconds_t.h&gt;<br>
#include&nbsp;&lt;igris/types-generic/time_t.h&gt;<br>
<br>
/*&nbsp;The&nbsp;&lt;sys/time.h&gt;&nbsp;header&nbsp;defines&nbsp;the&nbsp;timeval&nbsp;structure&nbsp;that&nbsp;includes&nbsp;at&nbsp;least<br>
&nbsp;*&nbsp;the&nbsp;following&nbsp;members:<br>
&nbsp;*&nbsp;time_t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tv_sec&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seconds<br>
&nbsp;*&nbsp;suseconds_t&nbsp;&nbsp;&nbsp;&nbsp;tv_usec&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;microseconds<br>
&nbsp;*/<br>
struct&nbsp;timeval<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_t&nbsp;tv_sec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;suseconds_t&nbsp;tv_usec;<br>
};<br>
<br>
/*&nbsp;The&nbsp;&lt;sys/time.h&gt;&nbsp;header&nbsp;defines&nbsp;the&nbsp;itimerval&nbsp;structure&nbsp;that&nbsp;includes&nbsp;at<br>
&nbsp;*&nbsp;least&nbsp;the&nbsp;following&nbsp;members:<br>
&nbsp;*&nbsp;struct&nbsp;timeval&nbsp;it_interval&nbsp;timer&nbsp;interval<br>
&nbsp;*&nbsp;struct&nbsp;timeval&nbsp;it_value&nbsp;&nbsp;&nbsp;&nbsp;current&nbsp;value<br>
&nbsp;*/<br>
struct&nbsp;itimerval<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;timeval&nbsp;it_interval;&nbsp;/*&nbsp;Timer&nbsp;period.&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;timeval&nbsp;it_value;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Timer&nbsp;expiration.&nbsp;*/<br>
};<br>
<br>
#include&nbsp;&lt;sys/cdefs.h&gt;<br>
<br>
__BEGIN_DECLS<br>
<br>
extern&nbsp;int&nbsp;gettimeofday(struct&nbsp;timeval&nbsp;*ts,&nbsp;void&nbsp;*tz);<br>
<br>
/*&nbsp;TODO&nbsp;this&nbsp;is&nbsp;only&nbsp;for&nbsp;Linux&nbsp;*/<br>
struct&nbsp;timezone<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tz_minuteswest;&nbsp;/*&nbsp;minutes&nbsp;west&nbsp;of&nbsp;Greenwich&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tz_dsttime;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;type&nbsp;of&nbsp;DST&nbsp;correction&nbsp;*/<br>
};<br>
<br>
/*&nbsp;TODO&nbsp;Linux&nbsp;specific&nbsp;signature<br>
extern&nbsp;int&nbsp;gettimeofday(struct&nbsp;timeval&nbsp;*ts,&nbsp;struct&nbsp;timezone&nbsp;*tz);<br>
*/<br>
<br>
//&nbsp;TODO&nbsp;only&nbsp;Linux&nbsp;compatible<br>
/**<br>
&nbsp;*&nbsp;timeval&nbsp;operations<br>
&nbsp;*/<br>
<br>
extern&nbsp;void&nbsp;timeradd(struct&nbsp;timeval&nbsp;*a,&nbsp;struct&nbsp;timeval&nbsp;*b,&nbsp;struct&nbsp;timeval&nbsp;*r);<br>
<br>
extern&nbsp;void&nbsp;timersub(struct&nbsp;timeval&nbsp;*a,&nbsp;struct&nbsp;timeval&nbsp;*b,&nbsp;struct&nbsp;timeval&nbsp;*r);<br>
<br>
extern&nbsp;void&nbsp;timerclear(struct&nbsp;timeval&nbsp;*tvp);<br>
<br>
extern&nbsp;int&nbsp;timerisset(struct&nbsp;timeval&nbsp;*tvp);<br>
<br>
#define&nbsp;timercmp(a,&nbsp;b,&nbsp;CMP)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;(((a)-&gt;tv_sec&nbsp;CMP(b)-&gt;tv_sec)&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(((a)-&gt;tv_sec&nbsp;==&nbsp;(b)-&gt;tv_sec)&nbsp;&amp;&amp;&nbsp;((a)-&gt;tv_usec&nbsp;CMP(b)-&gt;tv_usec)))<br>
<br>
__END_DECLS<br>
<br>
#include&nbsp;&lt;sys/select.h&gt;<br>
<br>
#endif&nbsp;/*&nbsp;COMPAT_POSIX_SYS_TIME_H_&nbsp;*/<br>
<!-- END SCAT CODE -->
</body>
</html>
