<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/posix/fcntl.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;FCNTL_H_<br>
#define&nbsp;FCNTL_H_<br>
<br>
#include&nbsp;&lt;sys/cdefs.h&gt;<br>
#include&nbsp;&lt;sys/stat.h&gt;<br>
<br>
#include&nbsp;&lt;stdio.h&gt;<br>
<br>
__BEGIN_DECLS<br>
<br>
/*&nbsp;int&nbsp;open&nbsp;(const&nbsp;char&nbsp;*path,&nbsp;int&nbsp;__oflag);<br>
&nbsp;*&nbsp;int&nbsp;open&nbsp;(const&nbsp;char&nbsp;*path,&nbsp;int&nbsp;__oflag,&nbsp;mode_t&nbsp;mode);<br>
&nbsp;*/<br>
extern&nbsp;int&nbsp;open(const&nbsp;char&nbsp;*path,&nbsp;int&nbsp;__oflag);<br>
<br>
/*<br>
&nbsp;*&nbsp;shall&nbsp;be&nbsp;equivalent&nbsp;to:&nbsp;open(path,&nbsp;O_WRONLY|O_CREAT|O_TRUNC,&nbsp;mode)<br>
&nbsp;*/<br>
extern&nbsp;int&nbsp;creat(const&nbsp;char&nbsp;*pathname,&nbsp;mode_t&nbsp;mode);<br>
<br>
extern&nbsp;int&nbsp;fcntl(int&nbsp;fd,&nbsp;int&nbsp;cmd,&nbsp;...);<br>
<br>
/*&nbsp;fcntl&nbsp;commands&nbsp;*/<br>
#define&nbsp;F_GETFD&nbsp;0<br>
#define&nbsp;F_SETFD&nbsp;1<br>
#define&nbsp;F_GETPIPE_SZ&nbsp;2<br>
#define&nbsp;F_SETPIPE_SZ&nbsp;3<br>
<br>
#define&nbsp;F_GETLK&nbsp;4&nbsp;&nbsp;/*&nbsp;Get&nbsp;record&nbsp;locking&nbsp;information.&nbsp;*/<br>
#define&nbsp;F_SETLK&nbsp;5&nbsp;&nbsp;/*&nbsp;Set&nbsp;record&nbsp;locking&nbsp;information.&nbsp;*/<br>
#define&nbsp;F_SETLKW&nbsp;6&nbsp;/*&nbsp;Set&nbsp;record&nbsp;locking&nbsp;information;&nbsp;wait&nbsp;if&nbsp;blocked.&nbsp;*/<br>
<br>
/*&nbsp;Values&nbsp;for&nbsp;l_type&nbsp;used&nbsp;for&nbsp;record&nbsp;locking&nbsp;with&nbsp;fcntl()&nbsp;(the&nbsp;following&nbsp;values<br>
&nbsp;*&nbsp;are&nbsp;unique)&nbsp;are&nbsp;as&nbsp;follows:&nbsp;*/<br>
#define&nbsp;F_RDLCK&nbsp;7&nbsp;/*&nbsp;Shared&nbsp;or&nbsp;read&nbsp;lock.&nbsp;*/<br>
#define&nbsp;F_UNLCK&nbsp;8&nbsp;/*&nbsp;Unlock.&nbsp;*/<br>
#define&nbsp;F_WRLCK&nbsp;9&nbsp;/*&nbsp;Exclusive&nbsp;or&nbsp;write&nbsp;lock.&nbsp;*/<br>
<br>
#define&nbsp;F_GETFL&nbsp;10<br>
#define&nbsp;F_SETFL&nbsp;11<br>
#define&nbsp;F_DUPFD&nbsp;12<br>
<br>
/*&nbsp;fcntl&nbsp;flags&nbsp;*/<br>
#define&nbsp;O_ACCESS_MASK&nbsp;(O_RDONLY&nbsp;|&nbsp;O_WRONLY&nbsp;|&nbsp;O_RDWR)<br>
#define&nbsp;O_RDONLY&nbsp;0x0000&nbsp;&nbsp;/*&nbsp;Open&nbsp;for&nbsp;reading&nbsp;only&nbsp;*/<br>
#define&nbsp;O_WRONLY&nbsp;0x0001&nbsp;&nbsp;/*&nbsp;Open&nbsp;for&nbsp;writing&nbsp;only&nbsp;*/<br>
#define&nbsp;O_RDWR&nbsp;0x0002&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Open&nbsp;for&nbsp;reading&nbsp;and&nbsp;writing&nbsp;*/<br>
#define&nbsp;O_SPECIAL&nbsp;0x0004&nbsp;/*&nbsp;Open&nbsp;for&nbsp;special&nbsp;access&nbsp;*/<br>
#define&nbsp;O_APPEND&nbsp;0x0008&nbsp;&nbsp;/*&nbsp;Writes&nbsp;done&nbsp;at&nbsp;EOF&nbsp;*/<br>
<br>
#define&nbsp;O_CREAT&nbsp;0x0100&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Create&nbsp;and&nbsp;open&nbsp;file&nbsp;*/<br>
#define&nbsp;O_TRUNC&nbsp;0x0200&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Truncate&nbsp;file&nbsp;*/<br>
#define&nbsp;O_EXCL&nbsp;0x0400&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Open&nbsp;only&nbsp;if&nbsp;file&nbsp;doesn't&nbsp;already&nbsp;exist&nbsp;*/<br>
#define&nbsp;O_DIRECT&nbsp;0x0800&nbsp;&nbsp;&nbsp;/*&nbsp;Do&nbsp;not&nbsp;use&nbsp;cache&nbsp;for&nbsp;reads&nbsp;and&nbsp;writes&nbsp;*/<br>
#define&nbsp;O_NONBLOCK&nbsp;0x1000&nbsp;/*&nbsp;Non-blocking&nbsp;mode&nbsp;*/<br>
<br>
#define&nbsp;O_NOCTTY&nbsp;0x10000&nbsp;/*&nbsp;&nbsp;*/<br>
#define&nbsp;O_NDELAY&nbsp;0x01000&nbsp;/*	*/<br>
<br>
#define&nbsp;O_DIRECTORY&nbsp;0x2000&nbsp;/*&nbsp;Fail&nbsp;if&nbsp;not&nbsp;a&nbsp;directory.&nbsp;*/<br>
<br>
/*&nbsp;Open&nbsp;directory&nbsp;for&nbsp;search&nbsp;only.<br>
&nbsp;*&nbsp;The&nbsp;result&nbsp;is&nbsp;unspecified&nbsp;if&nbsp;this&nbsp;flag&nbsp;is&nbsp;applied&nbsp;to&nbsp;a&nbsp;non-directory&nbsp;file.<br>
&nbsp;*/<br>
#define&nbsp;O_SEARCH&nbsp;0x4000<br>
<br>
/*&nbsp;If&nbsp;path&nbsp;names&nbsp;a&nbsp;symbolic&nbsp;link,&nbsp;fail&nbsp;and&nbsp;set&nbsp;errno&nbsp;to&nbsp;[ELOOP]&nbsp;*/<br>
#define&nbsp;O_NOFOLLOW&nbsp;0x8000<br>
<br>
/*&nbsp;file&nbsp;descriptor&nbsp;flags&nbsp;*/<br>
#define&nbsp;FD_CLOEXEC&nbsp;0x0010<br>
/*&nbsp;TODO&nbsp;not&nbsp;POSIX&nbsp;*/<br>
#define&nbsp;O_CLOEXEC&nbsp;FD_CLOEXEC<br>
<br>
struct&nbsp;flock<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;short&nbsp;l_type;&nbsp;&nbsp;&nbsp;/*&nbsp;Type&nbsp;of&nbsp;lock;&nbsp;F_RDLCK,&nbsp;F_WRLCK,&nbsp;F_UNLCK.&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;short&nbsp;l_whence;&nbsp;/*&nbsp;Flag&nbsp;for&nbsp;starting&nbsp;offset.&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;off_t&nbsp;l_start;&nbsp;&nbsp;/*&nbsp;Relative&nbsp;offset&nbsp;in&nbsp;bytes.&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;off_t&nbsp;l_len;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Size;&nbsp;if&nbsp;0&nbsp;then&nbsp;until&nbsp;EOF.&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;pid_t&nbsp;l_pid;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Process&nbsp;ID&nbsp;of&nbsp;the&nbsp;process&nbsp;holding&nbsp;the&nbsp;lock;&nbsp;returned&nbsp;with<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;F_GETLK.&nbsp;*/<br>
};<br>
<br>
__END_DECLS<br>
<br>
#endif&nbsp;/*&nbsp;FCNTL_H_&nbsp;*/<br>
<!-- END SCAT CODE -->
</body>
</html>
