<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/posix/time.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file<br>
&nbsp;*&nbsp;@brief&nbsp;ISO&nbsp;C99&nbsp;Standard:&nbsp;7.23&nbsp;Date&nbsp;and&nbsp;time.<br>
&nbsp;*<br>
&nbsp;*&nbsp;@date&nbsp;24.11.09<br>
&nbsp;*&nbsp;@author&nbsp;Anton&nbsp;Bondarev<br>
&nbsp;*&nbsp;@author&nbsp;Ilia&nbsp;Vaprol<br>
&nbsp;*/<br>
<br>
#ifndef&nbsp;TIME_H_<br>
#define&nbsp;TIME_H_<br>
/*&nbsp;The&nbsp;clock_t,&nbsp;size_t,&nbsp;time_t,&nbsp;clockid_t,&nbsp;and&nbsp;timer_t&nbsp;&nbsp;types&nbsp;shall&nbsp;be&nbsp;defined<br>
&nbsp;*&nbsp;as&nbsp;described&nbsp;in&nbsp;&lt;sys/types.h&gt;&nbsp;.<br>
&nbsp;*/<br>
<br>
#include&nbsp;&lt;igris/types-generic/clock_t.h&gt;<br>
#include&nbsp;&lt;igris/types-generic/clockid_t.h&gt;<br>
#include&nbsp;&lt;igris/types-generic/size_t.h&gt;<br>
#include&nbsp;&lt;igris/types-generic/time_t.h&gt;<br>
#include&nbsp;&lt;igris/types-generic/timer_t.h&gt;<br>
<br>
/*&nbsp;This&nbsp;header&nbsp;igris/types-generic&nbsp;the&nbsp;following&nbsp;symbolic&nbsp;names:<br>
NULL<br>
&nbsp;&nbsp;&nbsp;&nbsp;Null&nbsp;pointer&nbsp;constant.<br>
CLK_TCK<br>
&nbsp;&nbsp;&nbsp;&nbsp;Number&nbsp;of&nbsp;clock&nbsp;ticks&nbsp;per&nbsp;second&nbsp;returned&nbsp;by&nbsp;the&nbsp;times()&nbsp;function&nbsp;(LEGACY).<br>
CLOCKS_PER_SEC<br>
&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;number&nbsp;used&nbsp;to&nbsp;convert&nbsp;the&nbsp;value&nbsp;returned&nbsp;by&nbsp;the&nbsp;clock()&nbsp;function&nbsp;into<br>
&nbsp;&nbsp;&nbsp;&nbsp;seconds.&nbsp;*/<br>
#include&nbsp;&lt;igris/types-generic/null.h&gt;<br>
<br>
/*&nbsp;The&nbsp;value&nbsp;of&nbsp;this&nbsp;macro&nbsp;is&nbsp;the&nbsp;number&nbsp;of&nbsp;clock&nbsp;ticks&nbsp;per&nbsp;second&nbsp;measured&nbsp;by<br>
&nbsp;*&nbsp;the&nbsp;clock&nbsp;function.<br>
&nbsp;*/<br>
#define&nbsp;CLOCKS_PER_SEC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;1000&nbsp;//&nbsp;TODO&nbsp;CLOCKS_PER_SEC&nbsp;should&nbsp;receive&nbsp;from&nbsp;clock_getres()<br>
<br>
/*&nbsp;This&nbsp;is&nbsp;an&nbsp;obsolete&nbsp;name&nbsp;for&nbsp;CLOCKS_PER_SEC.&nbsp;*/<br>
#define&nbsp;CLK_TCK&nbsp;CLOCKS_PER_SEC<br>
<br>
/*&nbsp;Parameters&nbsp;used&nbsp;to&nbsp;convert&nbsp;the&nbsp;time&nbsp;specific&nbsp;values&nbsp;*/<br>
#define&nbsp;MSEC_PER_SEC&nbsp;1000L<br>
#define&nbsp;USEC_PER_MSEC&nbsp;1000L<br>
#define&nbsp;NSEC_PER_USEC&nbsp;1000L<br>
#define&nbsp;USEC_PER_SEC&nbsp;1000000L<br>
#define&nbsp;NSEC_PER_SEC&nbsp;1000000000L<br>
<br>
//#include&nbsp;&lt;sys/time.h&gt;&nbsp;//TODO&nbsp;not&nbsp;standard&nbsp;but&nbsp;Linux&nbsp;compatible<br>
<br>
struct&nbsp;tm<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_sec;&nbsp;&nbsp;&nbsp;/*Seconds&nbsp;[0,60].*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_min;&nbsp;&nbsp;&nbsp;/*Minutes&nbsp;[0,59].*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_hour;&nbsp;&nbsp;/*Hour&nbsp;[0,23].&nbsp;&nbsp;&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_mday;&nbsp;&nbsp;/*Day&nbsp;of&nbsp;month&nbsp;[1,31].&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_mon;&nbsp;&nbsp;&nbsp;/*Month&nbsp;of&nbsp;year&nbsp;[0,11].&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_year;&nbsp;&nbsp;/*Years&nbsp;since&nbsp;1900&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_wday;&nbsp;&nbsp;/*Day&nbsp;of&nbsp;week&nbsp;[0,6]&nbsp;(Sunday&nbsp;=0).&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_yday;&nbsp;&nbsp;/*Day&nbsp;of&nbsp;year&nbsp;[0,365].&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;tm_isdst;&nbsp;/*Daylight&nbsp;Savings&nbsp;flag.&nbsp;*/<br>
};<br>
<br>
struct&nbsp;timespec<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;time_t&nbsp;tv_sec;&nbsp;/*&nbsp;Seconds&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;long&nbsp;tv_nsec;&nbsp;&nbsp;/*&nbsp;Nanoseconds&nbsp;*/<br>
};<br>
<br>
struct&nbsp;itimerspec<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;timespec&nbsp;it_interval;&nbsp;/*&nbsp;Interval&nbsp;for&nbsp;periodic&nbsp;timer&nbsp;*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;timespec&nbsp;it_value;&nbsp;&nbsp;&nbsp;&nbsp;/*&nbsp;Initial&nbsp;expiration&nbsp;*/<br>
};<br>
<br>
#include&nbsp;&lt;sys/cdefs.h&gt;<br>
__BEGIN_DECLS<br>
<br>
/**<br>
&nbsp;*&nbsp;Converts&nbsp;the&nbsp;calendar&nbsp;time&nbsp;t&nbsp;into&nbsp;a&nbsp;null-terminated&nbsp;string&nbsp;of&nbsp;the&nbsp;form<br>
&nbsp;*&nbsp;&quot;Wed&nbsp;Jun&nbsp;30&nbsp;21:49:08&nbsp;1993\n&quot;.<br>
&nbsp;*&nbsp;It&nbsp;uses&nbsp;static&nbsp;allocated&nbsp;buffer&nbsp;which&nbsp;might&nbsp;be&nbsp;overwritten&nbsp;by&nbsp;subsequent<br>
&nbsp;*&nbsp;calls&nbsp;to&nbsp;any&nbsp;of&nbsp;the&nbsp;date&nbsp;and&nbsp;time&nbsp;functions<br>
&nbsp;*/<br>
extern&nbsp;char&nbsp;*ctime(const&nbsp;time_t&nbsp;*timep);<br>
extern&nbsp;char&nbsp;*ctime_r(const&nbsp;time_t&nbsp;*t,&nbsp;char&nbsp;*buff);<br>
<br>
extern&nbsp;struct&nbsp;tm&nbsp;*gmtime(const&nbsp;time_t&nbsp;*timep);<br>
extern&nbsp;struct&nbsp;tm&nbsp;*gmtime_r(const&nbsp;time_t&nbsp;*timep,&nbsp;struct&nbsp;tm&nbsp;*result);<br>
<br>
extern&nbsp;time_t&nbsp;mktime(struct&nbsp;tm&nbsp;*tm);<br>
<br>
/*&nbsp;convert&nbsp;date&nbsp;and&nbsp;time&nbsp;to&nbsp;a&nbsp;string&nbsp;*/<br>
extern&nbsp;char&nbsp;*asctime(const&nbsp;struct&nbsp;tm&nbsp;*timeptr);<br>
<br>
extern&nbsp;struct&nbsp;tm&nbsp;*localtime(const&nbsp;time_t&nbsp;*timep);<br>
extern&nbsp;struct&nbsp;tm&nbsp;*localtime_r(const&nbsp;time_t&nbsp;*timep,&nbsp;struct&nbsp;tm&nbsp;*result);<br>
<br>
/*&nbsp;clocks&nbsp;from&nbsp;beginning&nbsp;of&nbsp;start&nbsp;system&nbsp;*/<br>
extern&nbsp;clock_t&nbsp;clock(void);<br>
<br>
#define&nbsp;CLOCK_REALTIME&nbsp;3<br>
#define&nbsp;TIMER_ABSTIME&nbsp;2<br>
#define&nbsp;CLOCK_MONOTONIC&nbsp;1<br>
<br>
extern&nbsp;int&nbsp;clock_getres(clockid_t&nbsp;clk_id,&nbsp;struct&nbsp;timespec&nbsp;*res);<br>
<br>
extern&nbsp;int&nbsp;clock_gettime(clockid_t&nbsp;clk_id,&nbsp;struct&nbsp;timespec&nbsp;*tp);<br>
<br>
extern&nbsp;int&nbsp;clock_settime(clockid_t&nbsp;clk_id,&nbsp;const&nbsp;struct&nbsp;timespec&nbsp;*tp);<br>
<br>
/*&nbsp;seconds&nbsp;from&nbsp;beginning&nbsp;of&nbsp;start&nbsp;system&nbsp;*/<br>
extern&nbsp;time_t&nbsp;time(time_t&nbsp;*t);<br>
<br>
/**&nbsp;Format&nbsp;date&nbsp;and&nbsp;time&nbsp;*/<br>
extern&nbsp;size_t<br>
strftime(char&nbsp;*s,&nbsp;size_t&nbsp;max,&nbsp;const&nbsp;char&nbsp;*fmt,&nbsp;const&nbsp;struct&nbsp;tm&nbsp;*tm);<br>
<br>
extern&nbsp;int&nbsp;nanosleep(const&nbsp;struct&nbsp;timespec&nbsp;*req,&nbsp;struct&nbsp;timespec&nbsp;*rem);<br>
<br>
static&nbsp;inline&nbsp;double&nbsp;difftime(time_t&nbsp;time1,&nbsp;time_t&nbsp;time0)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(time1&nbsp;-&nbsp;time0);<br>
}<br>
<br>
__END_DECLS<br>
<br>
#endif&nbsp;/*&nbsp;TIME_H_&nbsp;*/<br>
<!-- END SCAT CODE -->
</body>
</html>
