<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/posix/unistd.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
/**<br>
&nbsp;*&nbsp;@file<br>
&nbsp;*&nbsp;@brief&nbsp;POSIX&nbsp;Standard:&nbsp;2.10&nbsp;Symbolic&nbsp;Constants.<br>
&nbsp;*&nbsp;@details&nbsp;This&nbsp;file&nbsp;defines&nbsp;miscellaneous&nbsp;symbolic&nbsp;constants&nbsp;and&nbsp;types,<br>
&nbsp;*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;declares&nbsp;miscellaneous&nbsp;function.&nbsp;Now&nbsp;only&nbsp;sleep&nbsp;functions.<br>
&nbsp;*<br>
&nbsp;*&nbsp;@date&nbsp;24.11.09<br>
&nbsp;*&nbsp;@author&nbsp;Anton&nbsp;Bondarev<br>
&nbsp;*/<br>
<br>
#ifndef&nbsp;COMPAT_POSIX_UNISTD_H_<br>
#define&nbsp;COMPAT_POSIX_UNISTD_H_<br>
<br>
#include&nbsp;&lt;igris/compiler.h&gt;<br>
<br>
#include&nbsp;&lt;sys/cdefs.h&gt;<br>
#include&nbsp;&lt;sys/stat.h&gt;<br>
#include&nbsp;&lt;sys/types.h&gt;<br>
<br>
#include&nbsp;&lt;sys/uio.h&gt;<br>
<br>
//#include&nbsp;&lt;posix_environ.h&gt;<br>
<br>
/*<br>
&nbsp;*&nbsp;The&nbsp;following&nbsp;symbolic&nbsp;constants&nbsp;are&nbsp;defined&nbsp;for&nbsp;sysconf():<br>
&nbsp;*/<br>
#define&nbsp;_SC_PAGESIZE&nbsp;1<br>
#define&nbsp;_SC_PAGE_SIZE&nbsp;_SC_PAGESIZE<br>
#define&nbsp;_SC_CLK_TCK&nbsp;2<br>
#define&nbsp;_SC_GETPW_R_SIZE_MAX&nbsp;3<br>
/*not&nbsp;posix&nbsp;*/<br>
#define&nbsp;_SC_NPROCESSORS_ONLN&nbsp;103<br>
#define&nbsp;_SC_NPROCESSORS_CONF&nbsp;_SC_NPROCESSORS_ONLN<br>
#define&nbsp;_SC_PHYS_PAGES&nbsp;104<br>
<br>
/*<br>
_SC_2_C_BIND<br>
_SC_2_C_DEV<br>
_SC_2_C_VERSION<br>
_SC_2_FORT_DEV<br>
_SC_2_FORT_RUN<br>
_SC_2_LOCALEDEF<br>
_SC_2_SW_DEV<br>
_SC_2_UPE<br>
_SC_2_VERSION<br>
_SC_ARG_MAX<br>
_SC_AIO_LISTIO_MAX<br>
_SC_AIO_MAX<br>
_SC_AIO_PRIO_DELTA_MAX<br>
_SC_ASYNCHRONOUS_IO<br>
_SC_ATEXIT_MAX<br>
_SC_BC_BASE_MAX<br>
_SC_BC_DIM_MAX<br>
_SC_BC_SCALE_MAX<br>
_SC_BC_STRING_MAX<br>
_SC_CHILD_MAX<br>
_SC_COLL_WEIGHTS_MAX<br>
_SC_DELAYTIMER_MAX<br>
_SC_EXPR_NEST_MAX<br>
_SC_FSYNC<br>
_SC_GETGR_R_SIZE_MAX<br>
_SC_GETPW_R_SIZE_MAX<br>
_SC_IOV_MAX<br>
_SC_JOB_CONTROL<br>
_SC_LINE_MAX<br>
_SC_LOGIN_NAME_MAX<br>
_SC_MAPPED_FILES<br>
_SC_MEMLOCK<br>
_SC_MEMLOCK_RANGE<br>
_SC_MEMORY_PROTECTION<br>
_SC_MESSAGE_PASSING<br>
_SC_MQ_OPEN_MAX<br>
_SC_MQ_PRIO_MAX<br>
_SC_NGROUPS_MAX<br>
_SC_OPEN_MAX<br>
_SC_PAGE_SIZE<br>
_SC_PASS_MAX&nbsp;(LEGACY)<br>
_SC_PRIORITIZED_IO<br>
_SC_PRIORITY_SCHEDULING<br>
_SC_RE_DUP_MAX<br>
<br>
<br>
_SC_REALTIME_SIGNALS<br>
_SC_RTSIG_MAX<br>
_SC_SAVED_IDS<br>
_SC_SEMAPHORES<br>
_SC_SEM_NSEMS_MAX<br>
_SC_SEM_VALUE_MAX<br>
_SC_SHARED_MEMORY_OBJECTS<br>
_SC_SIGQUEUE_MAX<br>
_SC_STREAM_MAX<br>
_SC_SYNCHRONIZED_IO<br>
_SC_THREADS<br>
_SC_THREAD_ATTR_STACKADDR<br>
_SC_THREAD_ATTR_STACKSIZE<br>
_SC_THREAD_DESTRUCTOR_ITERATIONS<br>
_SC_THREAD_KEYS_MAX<br>
_SC_THREAD_PRIORITY_SCHEDULING<br>
_SC_THREAD_PRIO_INHERIT<br>
_SC_THREAD_PRIO_PROTECT<br>
_SC_THREAD_PROCESS_SHARED<br>
_SC_THREAD_SAFE_FUNCTIONS<br>
_SC_THREAD_STACK_MIN<br>
_SC_THREAD_THREADS_MAX<br>
_SC_TIMERS<br>
_SC_TIMER_MAX<br>
_SC_TTY_NAME_MAX<br>
_SC_TZNAME_MAX<br>
_SC_VERSION<br>
_SC_XOPEN_VERSION<br>
_SC_XOPEN_CRYPT<br>
_SC_XOPEN_ENH_I18N<br>
_SC_XOPEN_SHM<br>
_SC_XOPEN_UNIX<br>
_SC_XOPEN_XCU_VERSION<br>
_SC_XOPEN_LEGACY<br>
_SC_XOPEN_REALTIME<br>
_SC_XOPEN_REALTIME_THREADS<br>
_SC_XBS5_ILP32_OFF32<br>
_SC_XBS5_ILP32_OFFBIG<br>
_SC_XBS5_LP64_OFF64<br>
_SC_XBS5_LPBIG_OFFBIG<br>
*/<br>
<br>
/*&nbsp;Standard&nbsp;file&nbsp;descriptors.&nbsp;*/<br>
#define&nbsp;STDIN_FILENO&nbsp;0&nbsp;&nbsp;/*&nbsp;Standard&nbsp;input.&nbsp;*/<br>
#define&nbsp;STDOUT_FILENO&nbsp;1&nbsp;/*&nbsp;Standard&nbsp;output.&nbsp;*/<br>
#define&nbsp;STDERR_FILENO&nbsp;2&nbsp;/*&nbsp;Standard&nbsp;error&nbsp;output.&nbsp;*/<br>
<br>
/*&nbsp;Values&nbsp;for&nbsp;the&nbsp;WHENCE&nbsp;argument&nbsp;to&nbsp;lseek.&nbsp;*/<br>
#define&nbsp;SEEK_SET&nbsp;0&nbsp;/*&nbsp;Seek&nbsp;from&nbsp;beginning&nbsp;of&nbsp;file.&nbsp;*/<br>
#define&nbsp;SEEK_CUR&nbsp;1&nbsp;/*&nbsp;Seek&nbsp;from&nbsp;current&nbsp;position.&nbsp;*/<br>
#define&nbsp;SEEK_END&nbsp;2&nbsp;/*&nbsp;Seek&nbsp;from&nbsp;end&nbsp;of&nbsp;file.&nbsp;*/<br>
<br>
__BEGIN_DECLS<br>
/**<br>
&nbsp;*&nbsp;suspend&nbsp;execution&nbsp;for&nbsp;an&nbsp;interval&nbsp;of&nbsp;time<br>
&nbsp;*&nbsp;@param&nbsp;seconds&nbsp;interval&nbsp;in&nbsp;seconds<br>
&nbsp;*&nbsp;@return&nbsp;0&nbsp;if&nbsp;time&nbsp;has&nbsp;elapsed&nbsp;if&nbsp;was&nbsp;error&nbsp;then&nbsp;return&nbsp;-1<br>
&nbsp;*/<br>
extern&nbsp;int&nbsp;sleep(unsigned&nbsp;int&nbsp;seconds);<br>
<br>
/**<br>
&nbsp;*&nbsp;suspend&nbsp;execution&nbsp;for&nbsp;an&nbsp;interval&nbsp;of&nbsp;time<br>
&nbsp;*&nbsp;@param&nbsp;useconds&nbsp;interval&nbsp;in&nbsp;microseconds<br>
&nbsp;*&nbsp;@return&nbsp;0&nbsp;if&nbsp;time&nbsp;has&nbsp;elapsed&nbsp;if&nbsp;was&nbsp;error&nbsp;then&nbsp;return&nbsp;-1<br>
&nbsp;*/<br>
extern&nbsp;int&nbsp;usleep(useconds_t&nbsp;useconds);<br>
<br>
extern&nbsp;ssize_t&nbsp;write(int&nbsp;fd,&nbsp;const&nbsp;void&nbsp;*buf,&nbsp;size_t&nbsp;nbyte);<br>
<br>
extern&nbsp;ssize_t&nbsp;read(int&nbsp;fd,&nbsp;void&nbsp;*buf,&nbsp;size_t&nbsp;nbyte);<br>
<br>
extern&nbsp;ssize_t&nbsp;writev(int&nbsp;fd,&nbsp;const&nbsp;struct&nbsp;iovec&nbsp;*iov,&nbsp;int&nbsp;iovcnt);<br>
<br>
extern&nbsp;ssize_t&nbsp;readv(int&nbsp;fd,&nbsp;const&nbsp;struct&nbsp;iovec&nbsp;*iov,&nbsp;int&nbsp;iovcnt);<br>
<br>
extern&nbsp;off_t&nbsp;lseek(int&nbsp;fd,&nbsp;off_t&nbsp;offset,&nbsp;int&nbsp;origin);<br>
<br>
extern&nbsp;int&nbsp;close(int&nbsp;fd);<br>
<br>
extern&nbsp;int&nbsp;fsync(int);<br>
<br>
extern&nbsp;pid_t&nbsp;fork(void);<br>
extern&nbsp;pid_t&nbsp;vfork(void);<br>
<br>
extern&nbsp;int&nbsp;nice(int&nbsp;incr);<br>
<br>
extern&nbsp;int&nbsp;execv(const&nbsp;char&nbsp;*path,&nbsp;char&nbsp;*const&nbsp;argv[]);<br>
extern&nbsp;int&nbsp;execve(const&nbsp;char&nbsp;*filename,&nbsp;char&nbsp;*const&nbsp;argv[],&nbsp;char&nbsp;*const&nbsp;envp[]);<br>
<br>
extern&nbsp;int&nbsp;link(const&nbsp;char&nbsp;*oldpath,&nbsp;const&nbsp;char&nbsp;*newpath);<br>
extern&nbsp;ssize_t&nbsp;readlink(const&nbsp;char&nbsp;*path,&nbsp;char&nbsp;*buf,&nbsp;size_t&nbsp;bufsize);<br>
extern&nbsp;ssize_t&nbsp;readlinkat(int&nbsp;fd,&nbsp;const&nbsp;char&nbsp;*path,&nbsp;char&nbsp;*buf,&nbsp;size_t&nbsp;bufsize);<br>
<br>
extern&nbsp;int&nbsp;unlink(const&nbsp;char&nbsp;*pathname);<br>
<br>
extern&nbsp;int&nbsp;rmdir(const&nbsp;char&nbsp;*pathname);<br>
<br>
extern&nbsp;pid_t&nbsp;getpid(void);<br>
<br>
extern&nbsp;int&nbsp;isatty(int&nbsp;fd);<br>
<br>
extern&nbsp;int&nbsp;dup(int&nbsp;flides);<br>
extern&nbsp;int&nbsp;dup2(int&nbsp;flides,&nbsp;int&nbsp;flides2);<br>
<br>
extern&nbsp;int&nbsp;pipe(int&nbsp;pipefd[2]);<br>
extern&nbsp;int&nbsp;pipe2(int&nbsp;pipefd[2],&nbsp;int&nbsp;flags);<br>
<br>
extern&nbsp;void&nbsp;_NORETURN&nbsp;_exit(int&nbsp;status);<br>
<br>
extern&nbsp;uid_t&nbsp;getuid(void);<br>
extern&nbsp;uid_t&nbsp;geteuid(void);<br>
<br>
extern&nbsp;uid_t&nbsp;getgid(void);<br>
extern&nbsp;uid_t&nbsp;getegid(void);<br>
<br>
extern&nbsp;int&nbsp;setreuid(uid_t&nbsp;ruid,&nbsp;uid_t&nbsp;euid);<br>
extern&nbsp;int&nbsp;setuid(uid_t&nbsp;uid);<br>
extern&nbsp;int&nbsp;seteuid(uid_t&nbsp;uid);<br>
<br>
extern&nbsp;int&nbsp;setregid(gid_t&nbsp;rgid,&nbsp;gid_t&nbsp;egid);<br>
extern&nbsp;int&nbsp;setgid(gid_t&nbsp;gid);<br>
extern&nbsp;int&nbsp;setegid(gid_t&nbsp;gid);<br>
<br>
extern&nbsp;int&nbsp;truncate(const&nbsp;char&nbsp;*path,&nbsp;off_t&nbsp;length);<br>
extern&nbsp;int&nbsp;ftruncate(int&nbsp;fd,&nbsp;off_t&nbsp;length);<br>
<br>
extern&nbsp;char&nbsp;*getcwd(char&nbsp;*buff,&nbsp;size_t&nbsp;size);<br>
extern&nbsp;int&nbsp;chdir(const&nbsp;char&nbsp;*path);<br>
<br>
extern&nbsp;int&nbsp;getpagesize(void);<br>
<br>
extern&nbsp;long&nbsp;int&nbsp;sysconf(int&nbsp;name);<br>
<br>
#define&nbsp;R_OK&nbsp;4<br>
#define&nbsp;W_OK&nbsp;2<br>
#define&nbsp;X_OK&nbsp;1<br>
#define&nbsp;F_OK&nbsp;0<br>
static&nbsp;inline&nbsp;int&nbsp;access(const&nbsp;char&nbsp;*path,&nbsp;int&nbsp;amode)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)path;<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)amode;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
extern&nbsp;void&nbsp;swab(const&nbsp;void&nbsp;*bfrom,&nbsp;void&nbsp;*bto,&nbsp;ssize_t&nbsp;n);<br>
//#include&nbsp;&lt;getopt.h&gt;<br>
<br>
#ifndef&nbsp;environ<br>
/**<br>
&nbsp;*&nbsp;FIXME&nbsp;environ&nbsp;MUST&nbsp;have&nbsp;follow&nbsp;declaration:<br>
&nbsp;*&nbsp;but&nbsp;then&nbsp;how&nbsp;to&nbsp;do&nbsp;it&nbsp;different&nbsp;for&nbsp;all&nbsp;tasks<br>
&nbsp;*/<br>
extern&nbsp;char&nbsp;**environ;<br>
#endif<br>
<br>
#define&nbsp;PASS_MAX&nbsp;32<br>
extern&nbsp;char&nbsp;*getpass(const&nbsp;char&nbsp;*prompt);<br>
<br>
extern&nbsp;int&nbsp;gethostname(char&nbsp;*name,&nbsp;size_t&nbsp;len);<br>
<br>
extern&nbsp;int&nbsp;chown(const&nbsp;char&nbsp;*path,&nbsp;uid_t&nbsp;owner,&nbsp;gid_t&nbsp;group);<br>
<br>
/*******************************************<br>
&nbsp;*&nbsp;stubs<br>
&nbsp;*******************************************/<br>
static&nbsp;inline&nbsp;void&nbsp;sync(void)&nbsp;{}<br>
<br>
__END_DECLS<br>
<br>
#endif&nbsp;/*&nbsp;COMPAT_POSIX_UNISTD_H_&nbsp;*/<br>
<!-- END SCAT CODE -->
</body>
</html>
