#!/usr/bin/env python3
#coding: utf-8

import random
import hashlib
import os
import sys

from optparse import OptionParser

parser = OptionParser()
parser.add_option("-u", "--user", action="store_true",
	default=False, help="store in user directory")
parser.add_option("-r", "--regen", action="store_true",
	default=False, help="regenerate key")
parser.add_option("-l", "--length", default=128,
	help="length of key")

opts, args = parser.parse_args(sys.argv)

keylen = int(opts.length)

def genkey():
	randvalue = random.random()
	m = hashlib.sha512()
	m.update(str(randvalue).encode("utf-8"))
	return m.hexdigest()

def create_file(path, text):
	f = open(path, "w")
	f.write(text)

def read_file(path):
	f = open(path, "r")
	return f.read()

if opts.user:
	uffile = os.path.expanduser("~/.unical_key")
else:
	uffile = "/var/unical_key"

if not os.path.exists(uffile) or opts.regen:
	create_file(uffile, genkey())

text = read_file(uffile)

if keylen > len(text):
	print("lenhth should by less or equal 128")
	exit(-1)

print(text[0:keylen])