#ifndef ASM_GENERIC_LIMITS_BASE_H_
#define ASM_GENERIC_LIMITS_BASE_H_

#define INT8_MIN	(- INT8_MAX - 1)
#define INT8_MAX	0x7F
#define UINT8_MAX	0xFF

#define INT16_MIN	(- INT16_MAX - 1)
#define INT16_MAX	0x7FFF
#define UINT16_MAX	0xFFFF

#define INT32_MIN	(- INT32_MAX - 1)
#define INT32_MAX	0x7FFFFFFF
#define UINT32_MAX	0xFFFFFFFF

#define INT64_MIN	(- INT64_MAX - 1)
#define INT64_MAX	0x7FFFFFFFFFFFFFFF
#define UINT64_MAX	0xFFFFFFFFFFFFFFFF

#define INTMAX_MIN  INT64_MIN
#define INTMAX_MAX  INT64_MAX
#define UINTMAX_MAX UINT64_MAX

#endif