/**
    @file
*/

#ifndef CROW_DEFS_H
#define CROW_DEFS_H

#define CROW_UDPGATE_NO 12

#define G1_ACK_TYPE 0
#define G1_ACK21_TYPE 1
#define G1_ACK22_TYPE 2

#define CROW_NODE_PROTOCOL 3
#define CROW_PUBSUB_PROTOCOL 4

#define CROW_RPC_NODE_NO 2
#define CROWKER_BEAMSOCKET_BROCKER_NODE_NO 101
#define CROWKER_CONTROL_BROCKER_NODE_NO 100
#define CROWKER_SERVICE_BROCKER_NODE_NO 3
#define CTRANS_DEFAULT_PUBLISHER_NODE 99
#define CTRANS_DEFAULT_SUBSCRIBER_NODE 98
#define CTRANS_DEFAULT_REQUESTOR_NODE 97
#define CTRANS_DEFAULT_SERVICE_NODE 96
#define CTRANS_DEFAULT_BEAM_NODE 95

#define CROWKER_CONTROL_SERVICE_NID 6

#ifndef CROW_DEFAULT_QOS
#define CROW_DEFAULT_QOS 2
#endif

#ifndef CROW_DEFAULT_ACKQUANT
#define CROW_DEFAULT_ACKQUANT 50
#endif

#define CROW_DEFAULT_QUEUE_SIZE 1000

#endif
