<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/chardev.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;asm/irq.h&gt;<br>
#include&nbsp;&lt;genos/chardev.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
<br>
INIT_PRIORITY(140)<br>
static&nbsp;igris::dlist&lt;genos::chardev,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;genos::chardev::chardev_list_lnk&gt;&nbsp;chardev_list;<br>
<br>
genos::device_namespace_manager&nbsp;device_namespace;<br>
<br>
int&nbsp;genos::device_namespace_manager::lookup(genos::file_head&nbsp;**fh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*path)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(*fh&nbsp;==&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;dev&nbsp;:&nbsp;chardev_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(strcmp(dev.name(),&nbsp;path)&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*fh&nbsp;=&nbsp;&amp;dev;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
}<br>
<br>
genos::chardev::chardev(const&nbsp;char&nbsp;*name)&nbsp;:&nbsp;_name(name)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;chardev_list.move_back(*this);<br>
}<br>
<br>
genos::chardev::~chardev()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;chardev_list.pop(*this);<br>
}<br>
<br>
genos::zillot_chardev::zillot_chardev(zillot::chardev&nbsp;*zchar,&nbsp;const&nbsp;char&nbsp;*name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;genos::chardev(name),&nbsp;zchar(zchar)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;zchar-&gt;rx_callback&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;zillot_chardev::rx_callback,&nbsp;this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;zchar-&gt;tx_callback&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;igris::make_delegate(&amp;zillot_chardev::tx_callback,&nbsp;this);<br>
}<br>
<br>
int&nbsp;genos::zillot_chardev::write(const&nbsp;void&nbsp;*data,&nbsp;unsigned&nbsp;int&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;zchar-&gt;write(data,&nbsp;size);<br>
}<br>
<br>
int&nbsp;genos::zillot_chardev::read(void&nbsp;*data,&nbsp;unsigned&nbsp;int&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(data&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;wait_for_avail();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(zchar-&gt;avail()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wait_current_schedee(&amp;rx_wait,&nbsp;0,&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee_displace();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(data&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;zchar-&gt;read(data,&nbsp;size);<br>
}<br>
<br>
int&nbsp;genos::zillot_chardev::wait_for_avail()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqstate_t&nbsp;save&nbsp;=&nbsp;irqs_save();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(zchar-&gt;avail()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wait_current_schedee(&amp;rx_wait,&nbsp;0,&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqs_restore(save);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::zillot_chardev::on_open()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::zillot_chardev::on_release()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
void&nbsp;genos::zillot_chardev::rx_callback()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;unwait_one(&amp;rx_wait,&nbsp;0);<br>
}<br>
<br>
void&nbsp;genos::zillot_chardev::tx_callback()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;unwait_one(&amp;tx_wait,&nbsp;0);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
