<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/coop_schedee.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;asm/irq.h&gt;<br>
#include&nbsp;&lt;genos/coop_schedee.h&gt;<br>
#include&nbsp;&lt;genos/schedee.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
#include&nbsp;&lt;igris/defs/schedee.h&gt;<br>
#include&nbsp;&lt;igris/dprint.h&gt;<br>
#include&nbsp;&lt;igris/util/bug.h&gt;<br>
#include&nbsp;&lt;stdlib.h&gt;<br>
<br>
static&nbsp;void&nbsp;coop_schedee_starter(void&nbsp;*priv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::coop_schedee&nbsp;*csch&nbsp;=&nbsp;(genos::coop_schedee&nbsp;*)priv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;task&nbsp;=&nbsp;csch-&gt;task;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;arg&nbsp;=&nbsp;csch-&gt;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;ret&nbsp;=&nbsp;task(arg);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;if&nbsp;process&nbsp;is&nbsp;a&nbsp;child&nbsp;after&nbsp;fork&nbsp;(or&nbsp;something&nbsp;like&nbsp;ops)<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;then&nbsp;csch&nbsp;is&nbsp;not&nbsp;a&nbsp;current&nbsp;schedee.<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::coop_schedee&nbsp;*csch2&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(genos::coop_schedee&nbsp;*)genos::current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;csch2-&gt;ret&nbsp;=&nbsp;ret;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee_exit();<br>
}<br>
<br>
void&nbsp;genos::coop_schedee::execute()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_execmon.start_session();<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqs_enable();<br>
&nbsp;&nbsp;&nbsp;&nbsp;context_load(&amp;cntxt);<br>
}<br>
<br>
int&nbsp;genos::coop_schedee::displace()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_execmon.end_session();<br>
&nbsp;&nbsp;&nbsp;&nbsp;context_save_and_displace(&amp;cntxt);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;SCHEDEE_DISPLACE_REAL;<br>
}<br>
<br>
void&nbsp;genos::coop_schedee::finalize()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dynamic_heap_flag())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;free(heap);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;heap&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
genos::coop_schedee::~coop_schedee()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dynamic_heap_flag())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;free(heap);<br>
}<br>
<br>
genos::coop_schedee::coop_schedee(int&nbsp;(*task)(void&nbsp;*),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*arg,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*heapptr,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;heapsize,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;(*destructor)(schedee&nbsp;*))<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;schedee(destructor)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(heapsize);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;heap&nbsp;=&nbsp;heapptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;heapsize&nbsp;=&nbsp;heapsize;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(this-&gt;heap&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;heap&nbsp;=&nbsp;malloc(this-&gt;heapsize);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;set_dynamic_heap_flag();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;task&nbsp;=&nbsp;task;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;arg&nbsp;=&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;set_has_context_flag();<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;set_is_process_flag();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;context_init(&amp;cntxt,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(uintptr_t)this-&gt;heap&nbsp;+&nbsp;heapsize&nbsp;-&nbsp;1,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;coop_schedee_starter,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void&nbsp;*)this,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1);<br>
}<br>
<br>
genos::coop_schedee&nbsp;*genos::create_coop_schedee(int&nbsp;(*foo)(void&nbsp;*),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*arg,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*stack,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;stacksize)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;genos::create_process(foo,&nbsp;arg,&nbsp;stack,&nbsp;stacksize);<br>
}<br>
<br>
genos::coop_schedee&nbsp;*genos::create_process(int&nbsp;(*foo)(void&nbsp;*),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*arg,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;*stack,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;stack_heap_size)<br>
<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::coop_schedee&nbsp;*csch&nbsp;=&nbsp;new&nbsp;genos::coop_schedee(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;foo,&nbsp;arg,&nbsp;stack,&nbsp;stack_heap_size,&nbsp;+[](schedee&nbsp;*csch)&nbsp;{&nbsp;delete&nbsp;csch;&nbsp;});<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;csch;<br>
}<br>
<br>
void&nbsp;genos::coop_schedee::reset_context(int&nbsp;(*task)(void&nbsp;*),&nbsp;void&nbsp;*arg)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris::syslock_guard&nbsp;guard;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;task&nbsp;=&nbsp;task;<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;arg&nbsp;=&nbsp;arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;context_init(&amp;cntxt,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(uintptr_t)heap&nbsp;+&nbsp;heapsize&nbsp;-&nbsp;1,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;coop_schedee_starter,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void&nbsp;*)this,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
