<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/fork.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;asm/irq.h&gt;<br>
#include&nbsp;&lt;genos/coop_schedee.h&gt;<br>
#include&nbsp;&lt;genos/fork.h&gt;<br>
#include&nbsp;&lt;genos/invoke.h&gt;<br>
#include&nbsp;&lt;genos/schedee.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
#include&nbsp;&lt;igris/osinter/ctrobj.h&gt;<br>
#include&nbsp;&lt;igris/util/string.h&gt;<br>
//#include&nbsp;&lt;nos/print.h&gt;<br>
<br>
extern&nbsp;&quot;C&quot;&nbsp;unsigned&nbsp;char&nbsp;is_interrupt_context();<br>
<br>
int&nbsp;genos::clone(int&nbsp;(*fn)(void&nbsp;*),&nbsp;void&nbsp;*arg,&nbsp;void&nbsp;*stack,&nbsp;size_t&nbsp;stack_size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(is_interrupt_context()&nbsp;==&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert(stack&nbsp;==&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*sch&nbsp;=&nbsp;genos::current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*ncsch&nbsp;=&nbsp;genos::create_coop_schedee(fn,&nbsp;arg,&nbsp;stack,&nbsp;stack_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ncsch-&gt;set_priority(sch-&gt;priority());<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::force_set_current_schedee(ncsch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ncsch-&gt;copy_open_resources_from(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::force_set_current_schedee(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;ncsch-&gt;start();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ncsch-&gt;pid;<br>
}<br>
<br>
/*int&nbsp;genos::command_process_v(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;argv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*env&nbsp;=&nbsp;new&nbsp;environment_vars;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;std::string&nbsp;&amp;str&nbsp;:&nbsp;argv)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;env-&gt;args.push_back(strdup(str.c_str()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;add&nbsp;NULL&nbsp;to&nbsp;the&nbsp;end&nbsp;of&nbsp;args<br>
&nbsp;&nbsp;&nbsp;&nbsp;env-&gt;args.push_back(nullptr);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;env-&gt;cmd&nbsp;=&nbsp;env-&gt;args[0];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*sch&nbsp;=&nbsp;genos::current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::coop_schedee&nbsp;*csch&nbsp;=&nbsp;(genos::coop_schedee&nbsp;*)sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;csch-&gt;reset_context(__execute_starter,&nbsp;env);<br>
&nbsp;&nbsp;&nbsp;&nbsp;csch-&gt;execute();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;unreachable&nbsp;code<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
}<br>
<br>
int&nbsp;genos::execute(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;vec)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;genos::command_process_v(vec);<br>
}<br>
<br>
int&nbsp;genos::execute(const&nbsp;char&nbsp;*cmd)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;splited&nbsp;=&nbsp;igris::split(cmd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;genos::execute(splited);<br>
}*/<br>
<br>
int&nbsp;genos::waitpid(intptr_t&nbsp;pid)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;genos::current_schedee();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;genos::schedee_state::wait_schedee;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;future&nbsp;=&nbsp;pid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee_displace();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::waitpid_without_displace(intptr_t&nbsp;pid)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;genos::current_schedee();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;genos::schedee_state::wait_schedee;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;future&nbsp;=&nbsp;pid;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
