<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/invoke.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;cstring&gt;<br>
#include&nbsp;&lt;genos/coop_schedee.h&gt;<br>
#include&nbsp;&lt;genos/fork.h&gt;<br>
#include&nbsp;&lt;genos/invoke.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
#include&nbsp;&lt;igris/time/systime.h&gt;<br>
#include&nbsp;&lt;igris/util/bug.h&gt;<br>
#include&nbsp;&lt;igris/util/string.h&gt;<br>
//#include&nbsp;&lt;nos/print.h&gt;<br>
#include&nbsp;&lt;unistd.h&gt;<br>
<br>
INIT_PRIORITY(110)<br>
genos::system_utility_aggregator&nbsp;system_utilities;<br>
<br>
int&nbsp;genos::invoke_program(const&nbsp;char&nbsp;*cmd,&nbsp;int&nbsp;argc,&nbsp;const&nbsp;char&nbsp;**argv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;invoke_program:&quot;,&nbsp;cmd);<br>
&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;size:&quot;,&nbsp;system_utilities.utilities().size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;util&nbsp;:&nbsp;system_utilities.utilities())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;util&nbsp;name:&quot;,&nbsp;util.name());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;system_utilities.invoke(cmd,&nbsp;argc,&nbsp;(char&nbsp;**)argv);<br>
}<br>
<br>
void&nbsp;genos::system_utility_aggregator::add_utility(const&nbsp;char&nbsp;*cmd,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_utility_func_t&nbsp;util)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;_utilities.push_back({cmd,&nbsp;util});<br>
}<br>
<br>
int&nbsp;genos::system_utility_aggregator::invoke(const&nbsp;char&nbsp;*cmd,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;argc,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;**argv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;util&nbsp;:&nbsp;_utilities)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(strcmp(util.name().c_str(),&nbsp;cmd)&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;util.invoke(argc,&nbsp;argv);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
}<br>
<br>
std::vector&lt;genos::system_utility&gt;&nbsp;&amp;<br>
genos::system_utility_aggregator::utilities()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_utilities;<br>
}<br>
<br>
void&nbsp;genos::register_system_utility(const&nbsp;char&nbsp;*cmd,&nbsp;system_utility_func_t&nbsp;util)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_utilities.add_utility(cmd,&nbsp;util);<br>
}<br>
<br>
struct&nbsp;environment_vars<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*cmd&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;const&nbsp;char&nbsp;*&gt;&nbsp;args&nbsp;=&nbsp;{};<br>
};<br>
<br>
int&nbsp;__execute_starter(void&nbsp;*arg)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*env&nbsp;=&nbsp;(environment_vars&nbsp;*)arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::invoke_program(env-&gt;cmd,&nbsp;env-&gt;args.size(),&nbsp;env-&gt;args.data());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;char&nbsp;*str&nbsp;:&nbsp;env-&gt;args)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;free((void&nbsp;*)str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;delete&nbsp;env;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;__system_v_second_half(void&nbsp;*arg)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;sechalf&nbsp;id:&quot;,&nbsp;genos::current_schedee()-&gt;pid);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*env&nbsp;=&nbsp;(environment_vars&nbsp;*)arg;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*sch&nbsp;=&nbsp;genos::current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::coop_schedee&nbsp;*csch&nbsp;=&nbsp;(genos::coop_schedee&nbsp;*)sch;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;csch-&gt;set_mnemo(&quot;sechalf&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;csch-&gt;reset_context(__execute_starter,&nbsp;env);<br>
&nbsp;&nbsp;&nbsp;&nbsp;csch-&gt;execute();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;unreachable&nbsp;code<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::system(const&nbsp;char&nbsp;*cmd)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;environment_vars&nbsp;*cvec&nbsp;=&nbsp;new&nbsp;environment_vars;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;splitted&nbsp;=&nbsp;igris::split(cmd,&nbsp;'&nbsp;');<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;str&nbsp;:&nbsp;splitted)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;args.push_back(strdup(str.c_str()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;args.push_back(nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;cmd&nbsp;=&nbsp;cvec-&gt;args[0];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;pid&nbsp;=&nbsp;genos::clone(__system_v_second_half,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void&nbsp;*)cvec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NULL,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GENOS_DEFAULT_HEAPSTACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::waitpid(pid);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::system_v(const&nbsp;char&nbsp;**cmds)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;abort();<br>
&nbsp;&nbsp;&nbsp;&nbsp;/*environment_vars&nbsp;*cvec&nbsp;=&nbsp;new&nbsp;environment_vars;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;char&nbsp;**sstr&nbsp;=&nbsp;cmds;&nbsp;*sstr&nbsp;!=&nbsp;NULL;&nbsp;++sstr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;args.push_back(strdup(*sstr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;args.push_back(nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;cmd&nbsp;=&nbsp;cvec-&gt;args[0];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;pid&nbsp;=&nbsp;genos::clone(__system_v_second_half,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void&nbsp;*)cvec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NULL,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GENOS_DEFAULT_HEAPSTACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::waitpid(pid);*/<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::system_v_without_displace(const&nbsp;char&nbsp;**argv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;environment_vars&nbsp;*cvec&nbsp;=&nbsp;new&nbsp;environment_vars;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;char&nbsp;**sstr&nbsp;=&nbsp;argv;&nbsp;*sstr&nbsp;!=&nbsp;NULL;&nbsp;++sstr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;args.push_back(strdup(*sstr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;args.push_back(nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;cvec-&gt;cmd&nbsp;=&nbsp;cvec-&gt;args[0];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;pid&nbsp;=&nbsp;genos::clone(__system_v_second_half,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void&nbsp;*)cvec,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NULL,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GENOS_DEFAULT_HEAPSTACK_SIZE);<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::waitpid_without_displace(pid);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
