<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/ktimer.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;genos/ktimer.h&gt;<br>
#include&nbsp;&lt;genos/schedee.h&gt;<br>
#include&nbsp;&lt;igris/dprint.h&gt;<br>
#include&nbsp;&lt;igris/time/jiffies-systime.h&gt;<br>
#include&nbsp;&lt;igris/time/systime.h&gt;<br>
#include&nbsp;&lt;stdlib.h&gt;<br>
<br>
igris::dlist&lt;genos::ktimer,&nbsp;&amp;genos::ktimer::lnk&gt;&nbsp;ktimer_list;<br>
<br>
uint8_t&nbsp;genos::ktimer::check(int64_t&nbsp;now)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;now&nbsp;-&nbsp;start&nbsp;&gt;=&nbsp;interval;<br>
}<br>
<br>
void&nbsp;genos::ktimer::set_start_now()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;start&nbsp;=&nbsp;jiffies();<br>
}<br>
void&nbsp;genos::ktimer::set_interval_ms(int64_t&nbsp;t)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;interval&nbsp;=&nbsp;ms2jiffies(t);<br>
}<br>
<br>
bool&nbsp;genos::ktimer::planned()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;lnk.is_linked();<br>
}<br>
<br>
void&nbsp;genos::ktimer::unplan()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;lnk.unlink();<br>
}<br>
<br>
void&nbsp;genos::ktimer::plan()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;final&nbsp;=&nbsp;start&nbsp;+&nbsp;interval;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;unplan();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;ktimer_list.begin();<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(;&nbsp;it&nbsp;!=&nbsp;ktimer_list.end();&nbsp;++it)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;it_final&nbsp;=&nbsp;it-&gt;start&nbsp;+&nbsp;it-&gt;interval;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(final&nbsp;-&nbsp;it_final&nbsp;&lt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;ktimer_list.move_prev(*this,&nbsp;it);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;ktimer_execute(genos::ktimer&nbsp;*tim)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;tim-&gt;lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;tim-&gt;act(tim-&gt;arg,&nbsp;tim);<br>
}<br>
<br>
void&nbsp;genos::ktimer_manager_step(int64_t&nbsp;now)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!ktimer_list.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::ktimer&nbsp;*it&nbsp;=&nbsp;&amp;ktimer_list.first();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it-&gt;check(now))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ktimer_execute(it);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;genos::ktimer_manager_step()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;now&nbsp;=&nbsp;igris::system_time();<br>
&nbsp;&nbsp;&nbsp;&nbsp;ktimer_manager_step(now);<br>
}<br>
<br>
size_t&nbsp;genos::ktimer_manager_planed_count()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ktimer_list.size();<br>
}<br>
<br>
void&nbsp;genos::ktimer_manager_init()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;pass<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
