<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/schedee.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;array&gt;<br>
#include&nbsp;&lt;genos/schedee.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
#include&nbsp;&lt;genos/signal.h&gt;<br>
#include&nbsp;&lt;igris/container/dlist.h&gt;<br>
#include&nbsp;&lt;igris/dprint.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;string&gt;<br>
<br>
INIT_PRIORITY(140)<br>
igris::dlist&lt;genos::schedee,&nbsp;&amp;genos::schedee::schedee_list_lnk&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee_list;<br>
<br>
std::array&lt;igris::dlist&lt;genos::schedee,&nbsp;&amp;genos::schedee::control_lnk&gt;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SCHEDEE_PRIORITY_TOTAL&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;runlist;<br>
igris::dlist&lt;genos::schedee,&nbsp;&amp;genos::schedee::control_lnk&gt;&nbsp;unstoplist;<br>
igris::dlist&lt;genos::schedee,&nbsp;&amp;genos::schedee::control_lnk&gt;&nbsp;waitlist;<br>
igris::dlist&lt;genos::schedee,&nbsp;&amp;genos::schedee::control_lnk&gt;&nbsp;finallist;<br>
<br>
uint16_t&nbsp;pid_counter&nbsp;=&nbsp;0;<br>
<br>
genos::schedee&nbsp;*__current_schedee&nbsp;=&nbsp;NULL;<br>
genos::schedee&nbsp;*genos::current_schedee()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;__current_schedee;<br>
}<br>
<br>
void&nbsp;genos::force_set_current_schedee(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;__current_schedee&nbsp;=&nbsp;sch;<br>
}<br>
<br>
uint16_t&nbsp;generate_new_pid()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;founded&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;do<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pid_counter++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pid_counter&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pid_counter++;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;founded&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;sch&nbsp;:&nbsp;genos::schedee_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pid_counter&nbsp;==&nbsp;sch.pid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;founded&nbsp;=&nbsp;true;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;while&nbsp;(founded);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;pid_counter;<br>
}<br>
<br>
bool&nbsp;is_schedee_manager_lists_correct__DEBUG()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;SCHEDEE_PRIORITY_TOTAL;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!runlist[i].is_correct())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abort();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!waitlist.is_correct())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abort();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!unstoplist.is_correct())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abort();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!finallist.is_correct())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abort();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;<br>
}<br>
<br>
genos::schedee::schedee(void&nbsp;(*destructor)(schedee&nbsp;*sched))<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;destructor(destructor)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;destructor&nbsp;=&nbsp;destructor;<br>
&nbsp;&nbsp;&nbsp;&nbsp;u.flags&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;restbl.clear();<br>
&nbsp;&nbsp;&nbsp;&nbsp;local_errno&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;syslock_counter_save&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;pid&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gid&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch_state&nbsp;=&nbsp;schedee_state::stop;<br>
&nbsp;&nbsp;&nbsp;&nbsp;prio&nbsp;=&nbsp;SCHEDEE_PRIORITY_TOTAL&nbsp;-&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;parent&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;signal_handler&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;_mnemo&nbsp;=&nbsp;&quot;undefined&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;u.f.remove_without_zombie_state&nbsp;=&nbsp;1;<br>
}<br>
<br>
void&nbsp;genos::schedee::kill()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(u.f.killed)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;u.f.killed&nbsp;=&nbsp;1;<br>
}<br>
<br>
void&nbsp;genos::schedee_manager_init()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;list&nbsp;:&nbsp;runlist)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list.clear();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;waitlist.clear();<br>
&nbsp;&nbsp;&nbsp;&nbsp;unstoplist.clear();<br>
&nbsp;&nbsp;&nbsp;&nbsp;finallist.clear();<br>
}<br>
<br>
void&nbsp;genos::schedee_start(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;schedee_state::run;<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;sch-&gt;ctr.type&nbsp;=&nbsp;CTROBJ_SCHEDEE_LIST;<br>
&nbsp;&nbsp;&nbsp;&nbsp;unstoplist.move_back(*sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;genos::schedee_stop(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;schedee_state::stop;<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;sch-&gt;ctr.type&nbsp;=&nbsp;CTROBJ_SCHEDEE_LIST;<br>
&nbsp;&nbsp;&nbsp;&nbsp;waitlist.move_back(*sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
}<br>
<br>
void&nbsp;__schedee_run(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;runlist[sch-&gt;prio].move_back(*sch);<br>
}<br>
<br>
void&nbsp;schedee_notify_finalize(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sch&nbsp;&amp;&amp;&nbsp;sch-&gt;parent)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;parent-&gt;signal_received(SIGCHLD);<br>
}<br>
<br>
void&nbsp;genos::__schedee_final(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;tmp_current&nbsp;=&nbsp;current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;__current_schedee&nbsp;=&nbsp;sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;schedee_state::final;<br>
&nbsp;&nbsp;&nbsp;&nbsp;schedee_notify_finalize(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;finallist.move_back(*sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;__current_schedee&nbsp;=&nbsp;tmp_current;<br>
}<br>
<br>
void&nbsp;__schedee_execute(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;__current_schedee&nbsp;=&nbsp;sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;set_runned_flag();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;execute();<br>
}<br>
<br>
void&nbsp;genos::schedee_manager_step()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Отрабатываем&nbsp;логику&nbsp;завершения&nbsp;процессов.<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!finallist.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;&amp;finallist.front();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;schedee_list_lnk.unlink();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;schedee_state::zombie;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;finalize();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sch-&gt;remove_without_zombie_state_flag())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;schedee_deinit(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;destructor(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Перемещаем&nbsp;процессы,&nbsp;объявленные&nbsp;запущенными&nbsp;в&nbsp;основные&nbsp;листы.<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(!unstoplist.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;&amp;unstoplist.front();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;__schedee_run(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;priolvl&nbsp;=&nbsp;0;&nbsp;priolvl&nbsp;&lt;&nbsp;SCHEDEE_PRIORITY_TOTAL;&nbsp;priolvl++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!runlist[priolvl].empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;&amp;runlist[priolvl].front();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sch-&gt;killed_flag())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;__schedee_final(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;runlist[sch-&gt;prio].move_back(*sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;__schedee_execute(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Nobody&nbsp;to&nbsp;run<br>
&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
}<br>
<br>
void&nbsp;genos::schedee_deinit(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;schedee_list_lnk.unlink();<br>
}<br>
<br>
void&nbsp;genos::schedee::start()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!schedee_list_lnk.is_linked())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee_list.move_back(*this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(this-&gt;pid&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;pid&nbsp;=&nbsp;generate_new_pid();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee_start(this);<br>
}<br>
<br>
void&nbsp;genos::schedee::stop()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee_stop(this);<br>
}<br>
<br>
const&nbsp;char&nbsp;*genos::schedee_state_to_sting(genos::schedee_state&nbsp;state)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(state)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;genos::schedee_state::run:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;RUN&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;genos::schedee_state::stop:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;STOP&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;genos::schedee_state::final:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;FINAL&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;genos::schedee_state::zombie:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;ZOMBIE&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;UNKNOWN&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
std::string&nbsp;genos::schedee::info()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;str;<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;+=&nbsp;&quot;pid:&nbsp;&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;+=&nbsp;std::to_string(pid);<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;+=&nbsp;&quot;state:&nbsp;&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;+=&nbsp;schedee_state_to_sting(sch_state);<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;+=&nbsp;&quot;prio:&nbsp;&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;str;<br>
}<br>
<br>
void&nbsp;genos::schedee::signal_received(int&nbsp;sig)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sig&nbsp;==&nbsp;SIGCHLD&nbsp;&amp;&amp;&nbsp;sch_state&nbsp;==&nbsp;schedee_state::wait_schedee)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;*cursch&nbsp;=&nbsp;genos::current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;pid&nbsp;=&nbsp;cursch-&gt;future;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pid&nbsp;==&nbsp;cursch-&gt;pid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this-&gt;start();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(signal_handler)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;signal_handler(sig);<br>
}<br>
<br>
void&nbsp;genos::schedee::copy_open_resources_from(genos::schedee&nbsp;*sch)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;other_res&nbsp;=&nbsp;sch-&gt;resource_table();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;my_res&nbsp;=&nbsp;this-&gt;resource_table();<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;other_res.size();&nbsp;i++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;res&nbsp;=&nbsp;other_res[i];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;my_res.open_new_as(res);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
