<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/schedee_api.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;genos/displace.h&gt;<br>
#include&nbsp;&lt;genos/ktimer.h&gt;<br>
#include&nbsp;&lt;genos/schedee.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;igris/util/bug.h&gt;<br>
<br>
using&nbsp;namespace&nbsp;genos;<br>
<br>
int&nbsp;genos::wait_for_avail(unsigned&nbsp;int&nbsp;fd)<br>
{<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::resource_table&nbsp;&amp;resources&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee()-&gt;resource_table();<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(resources.size()&nbsp;&lt;=&nbsp;fd)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;openr&nbsp;=&nbsp;resources[fd];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;ret&nbsp;=&nbsp;openr.wait_for_avail();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ret;<br>
}<br>
<br>
void&nbsp;genos::current_schedee_exit()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch&nbsp;=&nbsp;current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;__schedee_final(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;displace();<br>
}<br>
<br>
int&nbsp;genos::current_schedee_displace()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch&nbsp;=&nbsp;current_schedee();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;syslock_counter_save&nbsp;=&nbsp;syslock_counter();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sch-&gt;displace();<br>
}<br>
<br>
void&nbsp;__timer_schedee_unsleep(void&nbsp;*priv,&nbsp;genos::ktimer&nbsp;*tim)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)tim;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch&nbsp;=&nbsp;(genos::schedee&nbsp;*)priv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;schedee_start(sch);<br>
}<br>
<br>
int&nbsp;genos::current_schedee_msleep(unsigned&nbsp;int&nbsp;ms,&nbsp;int64_t&nbsp;start)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;current_schedee_msleep_without_displace(ms,&nbsp;start);<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;re&nbsp;=&nbsp;current_schedee_displace();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;re;<br>
}<br>
<br>
int&nbsp;genos::current_schedee_msleep(unsigned&nbsp;int&nbsp;ms)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;genos::current_schedee_msleep(ms,&nbsp;igris::system_time());<br>
}<br>
<br>
void&nbsp;genos::current_schedee_msleep_without_displace(unsigned&nbsp;int&nbsp;ms,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int64_t&nbsp;start)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::ktimer&nbsp;*timer;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;current_schedee();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sch&nbsp;==&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;timer&nbsp;=&nbsp;&amp;sch-&gt;ktimer;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;sch-&gt;ctr.type&nbsp;=&nbsp;CTROBJ_KTIMER_SCHEDEE;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;schedee_state::wait;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;timer-&gt;init(__timer_schedee_unsleep,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void&nbsp;*)sch,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;start,&nbsp;//&nbsp;start<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ms&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;interval<br>
&nbsp;&nbsp;&nbsp;&nbsp;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;timer-&gt;plan();<br>
}<br>
<br>
void&nbsp;genos::current_schedee_msleep_without_displace(unsigned&nbsp;int&nbsp;ms)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee_msleep_without_displace(ms,&nbsp;igris::system_time());<br>
}<br>
<br>
void&nbsp;genos::send_signal_to_group(int&nbsp;gid,&nbsp;int&nbsp;sig)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;pass<br>
}<br>
<br>
int&nbsp;genos::kill(pid_t&nbsp;pid)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;sch&nbsp;:&nbsp;genos::schedee_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sch.pid&nbsp;==&nbsp;pid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch.kill();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
