<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/wait.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;asm/irq.h&gt;<br>
#include&nbsp;&lt;genos/schedee.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
#include&nbsp;&lt;genos/wait.h&gt;<br>
<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
#include&nbsp;&lt;igris/util/bug.h&gt;<br>
#include&nbsp;&lt;igris/util/macro.h&gt;<br>
<br>
int&nbsp;unwait_schedee_waiter(struct&nbsp;waiter&nbsp;*w)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch&nbsp;=&nbsp;mcast_out(w,&nbsp;genos::schedee,&nbsp;waiter);<br>
&nbsp;&nbsp;&nbsp;&nbsp;schedee_start(sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
void&nbsp;_unwait_schedee(void&nbsp;*priv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch&nbsp;=&nbsp;(genos::schedee&nbsp;*)priv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;unwait_schedee_waiter(&amp;sch-&gt;waiter);<br>
}<br>
<br>
/**<br>
&nbsp;*&nbsp;Подписывает&nbsp;текущую&nbsp;единицу&nbsp;исполнения&nbsp;на&nbsp;очередь&nbsp;ожидания&nbsp;@head.<br>
&nbsp;*<br>
&nbsp;*&nbsp;Если&nbsp;единица&nbsp;исполнения&nbsp;не&nbsp;имеет&nbsp;флага&nbsp;can_displace,&nbsp;метод<br>
&nbsp;*&nbsp;current_schedee_displace&nbsp;вернёт&nbsp;-1&nbsp;вместо&nbsp;вытеснения&nbsp;контекста.&nbsp;Функция<br>
&nbsp;*&nbsp;завершится&nbsp;немедленно,&nbsp;а&nbsp;завершение&nbsp;исполнения&nbsp;возлагается&nbsp;на<br>
&nbsp;*&nbsp;пользовательский&nbsp;код.<br>
&nbsp;*<br>
&nbsp;*&nbsp;@head&nbsp;-&nbsp;очередь&nbsp;ожидания<br>
&nbsp;*&nbsp;@priority&nbsp;-&nbsp;приоритетность&nbsp;-&nbsp;добавляет&nbsp;токен&nbsp;в&nbsp;начало&nbsp;или&nbsp;конец&nbsp;очереди<br>
&nbsp;*&nbsp;@future&nbsp;-&nbsp;Указатель&nbsp;на&nbsp;слово&nbsp;для&nbsp;приёма&nbsp;возвращаемого&nbsp;значения.<br>
&nbsp;*&nbsp;*/<br>
int&nbsp;wait_current_schedee(igris::dlist_base&nbsp;*head,&nbsp;int&nbsp;priority,&nbsp;void&nbsp;**future)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)future;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;genos::current_schedee();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(sch&nbsp;==&nbsp;NULL)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;genos::schedee_state::wait;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Для&nbsp;лока&nbsp;используем&nbsp;апи&nbsp;прерываний,&nbsp;чтобы&nbsp;не&nbsp;нарушать&nbsp;консистентность<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;подсистемы&nbsp;syslock<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqstate_t&nbsp;save&nbsp;=&nbsp;irqs_save();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;waiter_delegate_init(&amp;sch-&gt;waiter,&nbsp;_unwait_schedee,&nbsp;(void&nbsp;*)sch);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(priority)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;head-&gt;move_front(sch-&gt;waiter.lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;head-&gt;move_back(sch-&gt;waiter.lnk);<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqs_restore(save);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;waitchild()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;genos::current_schedee();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;genos::schedee_state::wait_schedee;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;control_lnk.unlink();<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee_displace();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
/*int&nbsp;waitqueue_no_displace_wait(struct&nbsp;waitqueue&nbsp;*queue)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;priority&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;igris::dlist_node&nbsp;*head&nbsp;=&nbsp;&amp;queue-&gt;lst;<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::schedee&nbsp;*sch;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch&nbsp;=&nbsp;genos::current_schedee();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;ctr.type&nbsp;=&nbsp;CTROBJ_WAITER_SCHEDEE;<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;sch_state&nbsp;=&nbsp;genos::schedee_state::wait;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Для&nbsp;лока&nbsp;используем&nbsp;апи&nbsp;прерываний,&nbsp;чтобы&nbsp;не&nbsp;нарушать&nbsp;консистентность<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;подсистемы&nbsp;syslock<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqstate_t&nbsp;save&nbsp;=&nbsp;irqs_save();<br>
&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;ctr.lnk.unlink();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(priority)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;ctr.lnk.move_next_than(head);<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sch-&gt;ctr.lnk.move_prev_than(head);<br>
&nbsp;&nbsp;&nbsp;&nbsp;irqs_restore(save);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
*/<br>
<!-- END SCAT CODE -->
</body>
</html>
