#!/usr/bin/env python3

import os
import re
import shutil
import subprocess
import sys
import tempfile

#style_path = os.path.join(os.path.dirname(__file__), "..", "..", ".clang-format")

style="\"--style={"+", ".join([
"BasedOnStyle: LLVM",
"TabWidth: 4",
"IndentWidth: 4",
"ContinuationIndentWidth: 4",
"ObjCBlockIndentWidth: 4",
"NamespaceIndentation: All",
"BreakBeforeBraces: Allman",
"FixNamespaceComments: false",
]) + "}\""

print(style)
#exit()

def system(*args, **kwargs):
    print("PRE-HOOK: invoke:", args, kwargs)
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out


def main():
    modified = re.compile('^[AM]+\s+(?P<name>.*\.[c|cpp|h]$)', re.MULTILINE)
    files = system('git', 'status', '--porcelain')
    print("PRE-HOOK: clang-format for files:")
    files = modified.findall(files.decode("utf-8"))

    print(files)

    for f in files:
        cmdstr = f'clang-format {style} {f} -i'
        output = os.system(cmdstr)
        
        if output:
            print(output)
            sys.exit(-1)

        system("git", "add", f)


if __name__ == '__main__':
    main()
