/**
    @file
*/

#ifndef CROW_DEFS_H
#define CROW_DEFS_H

#define CROW_UDPGATE_NO 12

#define G1_ACK_TYPE 0
#define G1_ACK21_TYPE 1
#define G1_ACK22_TYPE 2

#define CROW_NODE_PROTOCOL 3
#define CROW_PUBSUB_PROTOCOL 4

#define CROWKER_CLI_NODE_NO 0
#define CROWKER_ALIVE_NODE_NO 1
#define CROW_RPC_NODE_NO 2

#define CROWKER_CONTROL_SERVICE_NID 6
#define CROW_FASTSEND_DEFAULT true

#endif
