#ifndef BOARD_DEFS_H
#define BOARD_DEFS_H

constexpr unsigned int TOTAL_CTRL_AXES = 2;

#define BOTTOM_LEVEL_PRESCALLER 40
#define BOTTOM_LEVEL_PERIOD 100
#define BOTTOM_LEVEL_TIMER_FREQ (168000000 / 4 * 2)

#define SERVE_TIM TIM4
#define SERVE_TIM_IRQn TIM4_IRQn

#endif