/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_CrowSubscriber */

#ifndef _Included_crow_CrowSubscriber
#define _Included_crow_CrowSubscriber
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     crow_CrowSubscriber
     * Method:    nativeNew
     * Signature: ()J
     */
    JNIEXPORT jlong JNICALL Java_crow_CrowSubscriber_nativeNew(JNIEnv *,
                                                               jobject);

    /*
     * Class:     crow_CrowSubscriber
     * Method:    subscribe
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_crow_CrowSubscriber_subscribe(JNIEnv *,
                                                              jobject);

#ifdef __cplusplus
}
#endif
#endif
