/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_HostAddr */

#ifndef _Included_crow_HostAddr
#define _Included_crow_HostAddr
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     crow_HostAddr
     * Method:    nativeNew
     * Signature: (Ljava/lang/String;)J
     */
    JNIEXPORT jlong JNICALL Java_crow_HostAddr_nativeNew(JNIEnv *, jobject,
                                                         jstring);

#ifdef __cplusplus
}
#endif
#endif
