/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_CrowSpamSubscriber */

#ifndef _Included_crow_CrowSpamSubscriber
#define _Included_crow_CrowSpamSubscriber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crow_CrowSpamSubscriber
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crow_CrowSpamSubscriber_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     crow_CrowSpamSubscriber
 * Method:    bind
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crow_CrowSpamSubscriber_bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     crow_CrowSpamSubscriber
 * Method:    subscribe
 * Signature: (ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_crow_CrowSpamSubscriber_subscribe
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     crow_CrowSpamSubscriber
 * Method:    resubscribe
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_crow_CrowSpamSubscriber_resubscribe
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
