/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_Crow */

#ifndef _Included_crow_Crow
#define _Included_crow_Crow
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     crow_Crow
     * Method:    init_crow_library
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_init_1crow_1library(JNIEnv *, jclass);

    /*
     * Class:     crow_Crow
     * Method:    diagnostic
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_diagnostic(JNIEnv *, jclass,
                                                     jboolean);

    /*
     * Class:     crow_Crow
     * Method:    start_spin
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_start_1spin(JNIEnv *, jclass);

    /*
     * Class:     crow_Crow
     * Method:    join_spin
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_join_1spin(JNIEnv *, jclass);

    /*
     * Class:     crow_Crow
     * Method:    stop_spin
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_stop_1spin(JNIEnv *, jclass,
                                                     jboolean);

    /*
     * Class:     crow_Crow
     * Method:    warn
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_warn(JNIEnv *, jclass, jstring);

    /*
     * Class:     crow_Crow
     * Method:    create_udpgate
     * Signature: (II)V
     */
    JNIEXPORT void JNICALL Java_crow_Crow_create_1udpgate(JNIEnv *, jclass,
                                                          jint, jint);

#ifdef __cplusplus
}
#endif
#endif
