/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_CrowNode */

#ifndef _Included_crow_CrowNode
#define _Included_crow_CrowNode
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     crow_CrowNode
     * Method:    bind
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_crow_CrowNode_bind__I(JNIEnv *, jobject, jint);

    /*
     * Class:     crow_CrowNode
     * Method:    bind
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_crow_CrowNode_bind__(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
