/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crow_CrowPublisher */

#ifndef _Included_crow_CrowPublisher
#define _Included_crow_CrowPublisher
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     crow_CrowPublisher
     * Method:    nativeNew
     * Signature: ()J
     */
    JNIEXPORT jlong JNICALL Java_crow_CrowPublisher_nativeNew(JNIEnv *,
                                                              jobject);

    /*
     * Class:     crow_CrowPublisher
     * Method:    set_crowker_address
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL
    Java_crow_CrowPublisher_set_1crowker_1address(JNIEnv *, jobject, jstring);

    /*
     * Class:     crow_CrowPublisher
     * Method:    set_theme
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_crow_CrowPublisher_set_1theme(JNIEnv *, jobject,
                                                              jstring);

    /*
     * Class:     crow_CrowPublisher
     * Method:    publish
     * Signature: ([B)V
     */
    JNIEXPORT void JNICALL Java_crow_CrowPublisher_publish___3B(JNIEnv *,
                                                                jobject,
                                                                jbyteArray);

    /*
     * Class:     crow_CrowPublisher
     * Method:    publish
     * Signature: (Lcrow/HostAddr;ILjava/lang/String;[BII)V
     */
    JNIEXPORT void JNICALL
    Java_crow_CrowPublisher_publish__Lcrow_HostAddr_2ILjava_lang_String_2_3BII(
        JNIEnv *, jobject, jobject, jint, jstring, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
