<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/drivers/tty.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;genos/drivers/tty.h&gt;<br>
#include&nbsp;&lt;genos/drivers/tty_driver.h&gt;<br>
#include&nbsp;&lt;genos/drivers/tty_linedisc.h&gt;<br>
#include&nbsp;&lt;genos/schedee_api.h&gt;<br>
<br>
genos::tty::tty(const&nbsp;char&nbsp;*name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::tty_driver&nbsp;*drv,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::tty_linedisc&nbsp;*ldisc)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;chardev(name),&nbsp;driver(drv),&nbsp;linedisc(ldisc)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;driver-&gt;attach_tty(this);<br>
&nbsp;&nbsp;&nbsp;&nbsp;linedisc-&gt;attach_tty(this);<br>
}<br>
<br>
int&nbsp;genos::tty::write(const&nbsp;void&nbsp;*data,&nbsp;unsigned&nbsp;int&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;linedisc-&gt;transmit((const&nbsp;char&nbsp;*)data,&nbsp;size);<br>
}<br>
<br>
int&nbsp;genos::tty::read(void&nbsp;*data,&nbsp;unsigned&nbsp;int&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(linedisc-&gt;avail()&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wait_current_schedee(&amp;rx_wait,&nbsp;0,&nbsp;nullptr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;genos::current_schedee_displace();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(data&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;linedisc-&gt;read((char&nbsp;*)data,&nbsp;size);<br>
}<br>
<br>
void&nbsp;genos::tty::receive_newchar(char&nbsp;c)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;linedisc-&gt;receive_newchar(c);<br>
}<br>
<br>
void&nbsp;genos::tty::send_signal(int&nbsp;sig)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;genos::send_signal_to_group(gid,&nbsp;sig);<br>
}<br>
<br>
int&nbsp;genos::tty::on_open()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;current_pid&nbsp;=&nbsp;genos::current_schedee()-&gt;pid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;is_opened&nbsp;=&nbsp;pid&nbsp;!=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_opened&nbsp;&amp;&amp;&nbsp;pid&nbsp;!=&nbsp;current_pid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;-1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pid&nbsp;=&nbsp;current_pid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gid&nbsp;=&nbsp;genos::current_schedee()-&gt;gid;<br>
&nbsp;&nbsp;&nbsp;&nbsp;reference_counter++;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
int&nbsp;genos::tty::on_release()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;reference_counter--;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(reference_counter&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pid&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gid&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
}<br>
<br>
void&nbsp;genos::tty::signal(int&nbsp;sig)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;tty&nbsp;signal&quot;);<br>
}<br>
<br>
size_t&nbsp;genos::tty::send_over_driver(const&nbsp;char&nbsp;*data,&nbsp;size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;driver-&gt;transmit(data,&nbsp;size);<br>
}<br>
<br>
void&nbsp;genos::tty::notify_readers()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;unwait_one(&amp;rx_wait,&nbsp;0);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
