<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>genos/drivers/zillot_tty_driver.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&lt;genos/drivers/zillot_tty_driver.h&gt;<br>
#include&nbsp;&lt;igris/sync/syslock.h&gt;<br>
<br>
size_t&nbsp;genos::zillot_tty_driver::transmit(const&nbsp;char&nbsp;*data,&nbsp;size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;size_t&nbsp;writed&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(size&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_lock();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(udev-&gt;cantx()&nbsp;&amp;&amp;&nbsp;txring.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;writed++;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;sendbyte(*(char&nbsp;*)data);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(size&nbsp;!=&nbsp;writed)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;curwrited&nbsp;=&nbsp;txring.write((char&nbsp;*)data&nbsp;+&nbsp;writed,&nbsp;size&nbsp;-&nbsp;writed);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(curwrited)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;ctrirqs(UART_CTRIRQS_TXON);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;writed&nbsp;+=&nbsp;curwrited;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;system_unlock();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;writed;<br>
}<br>
<br>
void&nbsp;genos::zillot_tty_driver::uartring_irq_handler(void&nbsp;*priv,&nbsp;int&nbsp;code)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(code)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;UART_IRQCODE_TX:<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uartring_irq_handler_tx(priv);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;UART_IRQCODE_RX:<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uartring_irq_handler_rx(priv);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;case&nbsp;UART_IRQCODE_TC:&nbsp;//fallthrow<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dprln(&quot;uring:&quot;,&nbsp;code);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;genos::zillot_tty_driver::uartring_irq_handler_tx(void&nbsp;*priv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;genos::zillot_tty_driver&nbsp;*uring&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(struct&nbsp;genos::zillot_tty_driver&nbsp;*)priv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(uring-&gt;txring.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uring-&gt;udev-&gt;ctrirqs(UART_CTRIRQS_TXOFF);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;uring-&gt;tx_callback.invoke();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;c&nbsp;=&nbsp;uring-&gt;txring.tail();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uring-&gt;txring.pop();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uring-&gt;udev-&gt;sendbyte(c);<br>
}<br>
<br>
void&nbsp;genos::zillot_tty_driver::uartring_irq_handler_rx(void&nbsp;*priv)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;struct&nbsp;genos::zillot_tty_driver&nbsp;*uring&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(struct&nbsp;genos::zillot_tty_driver&nbsp;*)priv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;c&nbsp;=&nbsp;uring-&gt;udev-&gt;recvbyte();<br>
&nbsp;&nbsp;&nbsp;&nbsp;uring-&gt;receive_newchar(c);<br>
}<br>
<br>
void&nbsp;genos::zillot_tty_driver::begin()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;udev&nbsp;=&nbsp;uart;<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;if&nbsp;(rxbuffer&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;rxbuffer&nbsp;=&nbsp;(char&nbsp;*)malloc(rxring.size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;if&nbsp;(txbuffer&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;txbuffer&nbsp;=&nbsp;(char&nbsp;*)malloc(txring.size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;handler&nbsp;=&nbsp;uartring_irq_handler;<br>
&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;handarg&nbsp;=&nbsp;(void&nbsp;*)this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;enable(1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;ctrirqs(UART_CTRIRQS_RXON);<br>
}<br>
<br>
void&nbsp;genos::zillot_tty_driver::setup(int32_t&nbsp;baud,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;char&nbsp;parity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;databits,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;stopbits)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;udev-&gt;setup(baud,&nbsp;parity,&nbsp;databits,&nbsp;stopbits);<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
